select * from customer;

-- total revenue generated by Male Vs Female

select 
	gender,
	sum(purchase_amount) total_revenue
from customer
group by gender;

-- which customers used a discount but still spent > avg purchase amount

select 
	customer_id,
	purchase_amount,
	discount_applied
from customer
where discount_applied = 'Yes'
and purchase_amount >= (select avg(purchase_amount) from customer);

--  which are the top 5 product with highest avg review rating

select 
	item_purchased,
	round(avg(review_rating::numeric),2) avg_rating
from customer
group by item_purchased
order by avg_rating desc limit 5;

-- compare the avg purchase amount between standard vs express shipping

select 
	shipping_type,
	round(avg(purchase_amount),2) avg_purchase_amount
from customer
where shipping_type in ('Express','Standard')
group by shipping_type;

-- Do subscribed customers spend more, compare avg spend and total revenue between subs and non-subs 

select 
	count(*) total_customer,
	subscription_status,
	sum(purchase_amount) total_evenue,
	round(avg(purchase_amount),2) avg_spend
from customer
group by subscription_status;

-- which 5 products have the highest % of purchase with discount applied

select 	
	count(*) total_count,
	discount_applied
from customer
group by discount_applied;

select 
	item_purchased,
	sum(purchase_amount) total_purchase_amount,
	discount_applied
from customer
where discount_applied = 'Yes'
group by item_purchased, discount_applied
order by total_purchase_amount desc limit 5;

select 
	item_purchased,
	round(100 * sum(
		case when discount_applied = 'Yes' then 1 else 0 end) / count(*),2) purchased_per
from customer
group by item_purchased
order by purchased_per desc limit 5;

-- segment customers into new , returning and loyal based on their total number of previous purchase, and show the count 
-- of each segment

select 
	customer_type,
	count(*) total_count
from
	(select 
		case when previous_purchases >= 20 then 'Loyal'
			 when  previous_purchases >= 10 then 'Returning'
			 else 'New' 
		end as customer_type
	from customer
	)
group by customer_type;
	
-- what are the top 3 most poloular purchased product within each category..

select * 
from(
	select 
		category,
		item_purchased,
		count(customer_id) total_order,
		sum(purchase_amount) total_amount,
		row_number () over(partition by category order by count(customer_id) desc ) product_rank
	from customer
	group by category, item_purchased
) 
where product_rank <= 3;

-- are the customers who are repeat buyers (more than 5 prevoius purchase) also likely to subcribe ?

select 
	subscription_status,
	count(*) repet_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- what is the revenue contribution of each age category

select
	age_group,
	sum(purchase_amount) total_revenue
from customer
group by age_group order by total_revenue desc;